baseurl = "/"
languageCode = "en-us"
title = "Wsl Blog"
theme = "hugo-xmin"
disqusShortname = "wsl-blog-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[params]
    description = "The online blog for all of Zach's projects, rambles, and stuff."
    footer = "&copy; [Z Wilder](/about/) 2020 | [Github](https://github.com/zwilder/)"
