baseurl = "/"
languageCode = "en-us"
title = "Wsl Blog"
theme = "hugo-xmin"
disqusShortname = "zwilder-github-io"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
summaryLength = 350

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name= "Archive"
    url= "/posts/"
    weight = 3
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
[[menu.main]]
    name = "Subscribe"
    url = "/subscribe/"
    weight = 6
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 7

[params]
    description = "The online blog for all of Zach's projects, rambles, and stuff."
    footer = "&copy; [Z Wilder](/about/) 2016-2023 | [Github](https://github.com/zwilder/)"
